### ISSUE TITLE
Ladybug is not working in latest 7.7 release

### ISSUE THREAD

**Issue by rvdstel** [ibissource/iaf#2353]
**Describe the issue**
Deployed new version FF! 7.7-20211013.103955 on DEV WAS8 and Ladybug is no longer working. It show an error line: 
[nl.nn.testtool.storage.StorageException: IOException reading report 3013 from bytes: nl.nn.testtool.Report; incompatible types for field endTime] [Could not find report with storate id '3013']

**Reporter**
Richard van der Stel

DEV Environment

**Screenshots**
![image](https://user-images.githubusercontent.com/35798481/137494276-3b55c5f5-a59e-4d4a-a247-f791ac2984bb.png)

**Configuration**

**Input**

**Environment**
FF! 7.7-20211013.103955: Ibis4Titan 398-4594029b-release7-7
Heap size: 696M, total JVM memory: 1536M
Free disk space: 9GB, total disk space: 10GB
Up since: 2021-10-15 15:07:02 (18m)

**Additional Environment**
 - DBMS: [e.g. Oracle, MSSQL, MariaDB, MySql, PostgreSQL]
 - Browser: [e.g. Chrome, Safari, Edge, Firefox]

**Additional Context**
2021-10-15 15:19:31,287 DEBUG [WebContainer : 9] null file.Reader - Reusing old metadata for report with storage id 3008
2021-10-15 15:19:31,287 DEBUG [WebContainer : 9] null file.Reader - Reusing old metadata for report with storage id 3009
2021-10-15 15:19:31,287 DEBUG [WebContainer : 9] null file.Reader - Reusing old metadata for report with storage id 3010
2021-10-15 15:19:31,287 DEBUG [WebContainer : 9] null file.Reader - Reusing old metadata for report with storage id 3011
2021-10-15 15:19:31,288 DEBUG [WebContainer : 9] null file.Reader - Reusing old metadata for report with storage id 3012
2021-10-15 15:19:31,288 DEBUG [WebContainer : 9] null file.Reader - Reusing old metadata for report with storage id 3013
2021-10-15 15:19:31,300 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:31,300 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:31,301 DEBUG [WebContainer : 9] null reports.TreePane - Display: /
2021-10-15 15:19:31,302 DEBUG [WebContainer : 9] null reports.TreePane - Display: /
2021-10-15 15:19:31,303 DEBUG [WebContainer : 9] null reports.TreePane - Display: /
2021-10-15 15:19:31,304 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:31,311 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:31,316 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:31,317 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:31,317 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:31,318 DEBUG [WebContainer : 9] null reports.TreePane - Display reports: Reports
2021-10-15 15:19:34,203 ERROR [WebContainer : 2] null file.Reader - IOException reading report 3013 from bytes: nl.nn.testtool.Report; incompatible types for field endTime
java.io.InvalidClassException: nl.nn.testtool.Report; incompatible types for field endTime
	at java.io.ObjectStreamClass.matchFields(ObjectStreamClass.java:2582) ~[?:1.8.0]
	at java.io.ObjectStreamClass.getReflector(ObjectStreamClass.java:2476) ~[?:1.8.0]
	at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:825) ~[?:1.8.0]
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:2147) ~[?:1.8.0]
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1993) ~[?:1.8.0]
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2306) ~[?:1.8.0]
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1810) ~[?:1.8.0]
	at java.io.ObjectInputStream.readObjectImpl(ObjectInputStream.java:606) ~[?:1.8.0]
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:511) ~[?:1.8.0]
	at nl.nn.testtool.storage.file.Reader.getReport(Reader.java:285) [ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at nl.nn.testtool.storage.file.Storage.getReport(Storage.java:141) [ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at nl.nn.testtool.echo2.Echo2Application.getReport(Echo2Application.java:254) [ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at nl.nn.testtool.echo2.reports.ReportsComponent.openReport(ReportsComponent.java:760) [ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at nl.nn.testtool.echo2.reports.ReportsComponent.actionPerformed(ReportsComponent.java:574) [ibis-ladybug-2.2-20210820.122759.jar:2.2-20210820.122759]
	at echopointng.TableEx.fireActionEvent(TableEx.java:496) [ibis-echo2-2.0.3.jar:2.0.3]
	at echopointng.TableEx.processInput(TableEx.java:467) [ibis-echo2-2.0.3.jar:2.0.3]
	at nextapp.echo2.app.update.ClientUpdateManager.process(ClientUpdateManager.java:116) [ibis-echo2-2.0.3.jar:2.0.3]
	at nextapp.echo2.app.update.UpdateManager.processClientUpdates(UpdateManager.java:89) [ibis-echo2-2.0.3.jar:2.0.3]
	at nextapp.echo2.webcontainer.ContainerSynchronizeService.renderUpdate(ContainerSynchronizeService.java:471) [ibis-echo2-2.0.3.jar:2.0.3]
	at nextapp.echo2.webrender.service.SynchronizeService.service(SynchronizeService.java:279) [ibis-echo2-2.0.3.jar:2.0.3]
	at nextapp.echo2.webrender.WebRenderServlet.process(WebRenderServlet.java:273) [ibis-echo2-2.0.3.jar:2.0.3]
	at nextapp.echo2.webrender.WebRenderServlet.doPost(WebRenderServlet.java:189) [ibis-echo2-2.0.3.jar:2.0.3]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595) [javax.j2ee.servlet.jar:?]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668) [javax.j2ee.servlet.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1233) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:782) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.handleRequest(ServletWrapper.java:481) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.servlet.ServletWrapperImpl.handleRequest(ServletWrapperImpl.java:178) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.invokeTarget(WebAppFilterChain.java:136) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:97) [com.ibm.ws.webcontainer.jar:?]
	at nl.nn.adapterframework.webcontrol.LoginFilter.doFilter(LoginFilter.java:226) [ibis-adapterframework-core-7.7-20211013.103955.jar:7.7-20211013.103955]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer.jar:?]
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71) [log4j-web-2.14.1.jar:2.14.1]
	at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:195) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterChain.doFilter(WebAppFilterChain.java:91) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.doFilter(WebAppFilterManager.java:967) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.filter.WebAppFilterManager.invokeFilters(WebAppFilterManager.java:1107) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.servlet.CacheServletWrapper.handleRequest(CacheServletWrapper.java:87) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.WebContainer.handleRequest(WebContainer.java:949) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.WSWebContainer.handleRequest(WSWebContainer.java:1817) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.webcontainer.channel.WCChannelLink.ready(WCChannelLink.java:213) [com.ibm.ws.webcontainer.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleDiscrimination(HttpInboundLink.java:463) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.handleNewRequest(HttpInboundLink.java:530) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpInboundLink.processRequest(HttpInboundLink.java:316) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.http.channel.inbound.impl.HttpICLReadCallback.complete(HttpICLReadCallback.java:88) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.ssl.channel.impl.SSLReadServiceContext$SSLReadCompletedCallback.complete(SSLReadServiceContext.java:1833) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.tcp.channel.impl.AioReadCompletionListener.futureCompleted(AioReadCompletionListener.java:175) [com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.AbstractAsyncFuture.invokeCallback(AbstractAsyncFuture.java:217) [com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.AsyncChannelFuture.fireCompletionActions(AsyncChannelFuture.java:161) [com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.AsyncFuture.completed(AsyncFuture.java:138) [com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.ResultHandler.complete(ResultHandler.java:204) [com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.ResultHandler.runEventProcessingLoop(ResultHandler.java:775) [com.ibm.ws.runtime.jar:?]
	at com.ibm.io.async.ResultHandler$2.run(ResultHandler.java:905) [com.ibm.ws.runtime.jar:?]
	at com.ibm.ws.util.ThreadPool$Worker.run(ThreadPool.java:1892) [com.ibm.ws.runtime.jar:?]
