### ISSUE TITLE
Active MQ fails on websphere after upgrading from 7.5 RC2

### ISSUE THREAD

**Issue by jjansenvr** [ibissource/iaf#2533]
**Describe the issue**
After an upgrade of the FF version on a websphere machine the adapters using JMS from activeMQ is not working

Connection: (JMSException) Failed to create connection: (ResourceAllocationException): (IllegalStateException): (NoClassDefFoundError) org.apache.activemq.artemis.utils.uri.BeanSupport (initialization failure): (LogConfigurationException): (LogConfigurationException): (LogConfigurationException) Class org.apache.commons.logging.impl.Log4JLogger does not implement Log 

**Reporter**
Jeroen Jansen van Rosendaal

**To Reproduce**
ibis4solifehub on test runs on 7.5 RC2 after upgrading the 7.6.1 version the adapter goes into state error 

it could be the version of the activemq-client is needing another slf4j-api version

**Screenshots**

```
7.6.1 or 7.6 RC2
```

**Additional Environment**
 - ActiveMQ Artemis Message Broker version 2.9.0
 - 

**Additional Context**
Add any other context about the problem here. (f.e. ladybug report / test adapter with larva test)

**Comment by jacodg** [comment]
Log4j version 1 needs to be on the classpath
